#开发环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/outschoolreaders
    username: dev
    password: abc123
server:
  port: 9301
default-password: abc123
upload-file-path: 
  E:\outschoolreaders #windows
  #/home/yanjisheng/outschoolreaders/upload #linux