#SpringBoot配置文件
spring:
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
      fail-on-self-references: false
  datasource:
    continue-on-error: true
    initialization-mode: always    schema: classpath:sql/CreateTable.sql
    sql-script-encoding: UTF-8  servlet:
    multipart:      max-request-size: 11MB      max-file-size: 10MB
logging:
  level:
    root: info
    cn.edu.jju.outschoolreaders: debug
  pattern:
    console: "[%p] %d %t -> %c.%M%n%m%n"
    file: "[%p] %d %t -> %c.%M%n%m%n"
  file: logs/OutschoolReaders.log
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.jju.outschoolreaders.model, cn.edu.jju.outschoolreaders.util
  configuration:
    auto-mapping-behavior: full
    jdbc-type-for-null: "NULL"
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    map-underscore-to-camel-case: false